"""The original CIC-IDS2017 release, in the two forms the publisher offers.

Every value below was read from the files downloaded through the
publisher's request form on 2026-10-09.
"""

from idsdata.model import Column, FileEntry, Label

FLOWS_FILES = (
    FileEntry(
        name='GeneratedLabelledFlows.zip',
        sha256='7bdbef286f8893f31c6db12105fa097fa5c2dcc6733179037a08129d150ea27a',
        size=283876488,
        kind='archive',
    ),
    FileEntry(
        name='Monday-WorkingHours.pcap_ISCX.csv',
        sha256='96f26aea87d513073769b48ce204c2921791149e1c6225f7db65a3fed7973820',
        size=268649908,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Monday-WorkingHours.pcap_ISCX.csv',
        rows=529918,
    ),
    FileEntry(
        name='Tuesday-WorkingHours.pcap_ISCX.csv',
        sha256='ae9c88e10c41a8eb1ff454ae98bc513454925097d0b0b57180f94e79de445815',
        size=174696560,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Tuesday-WorkingHours.pcap_ISCX.csv',
        rows=445909,
    ),
    FileEntry(
        name='Wednesday-workingHours.pcap_ISCX.csv',
        sha256='ed538e85b84181e8897dedb3d37d365982f44b27eccd67c477581a8b65f3d170',
        size=285642925,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Wednesday-workingHours.pcap_ISCX.csv',
        rows=692703,
    ),
    FileEntry(
        name='Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
        sha256='e3deaff483d18b53b100a441dff9b8919416df8876b4edcc0f0d1e4bf48397d0',
        size=92030223,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
        rows=170366,
        blank_rows=288602,
    ),
    FileEntry(
        name='Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
        sha256='d74238e054023c8bd4d8056650463cadb25c100fb0e26ebd4272c07b5c022c4b',
        size=108723183,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
        rows=288602,
    ),
    FileEntry(
        name='Friday-WorkingHours-Morning.pcap_ISCX.csv',
        sha256='c061cd98f39d8054aeaed6244a5129a20b3985983d0d022b860ae8aa07fe8d21',
        size=75386737,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Friday-WorkingHours-Morning.pcap_ISCX.csv',
        rows=191033,
    ),
    FileEntry(
        name='Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
        sha256='7e2ddaa80a5849ba629463296b6128436c161b4a32e8034bb5beae06b0c45e08',
        size=101874777,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
        rows=286467,
    ),
    FileEntry(
        name='Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
        sha256='1f779b4f0d78f9225554c4de53b5a2c07912b60dcd136ee4c5c1d0d2496b7cc4',
        size=96101069,
        archive='GeneratedLabelledFlows.zip',
        member='TrafficLabelling /Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
        rows=225745,
    ),
)

FLOWS_COLUMNS = (
    Column('Flow ID', 'flow_id', 'string'),
    Column(' Source IP', 'source_ip', 'string'),
    Column(' Source Port', 'source_port', 'int64'),
    Column(' Destination IP', 'destination_ip', 'string'),
    Column(' Destination Port', 'destination_port', 'int64'),
    Column(' Protocol', 'protocol', 'int64'),
    Column(' Timestamp', 'timestamp', 'string'),
    Column(' Flow Duration', 'flow_duration', 'int64'),
    Column(' Total Fwd Packets', 'total_fwd_packets', 'int64'),
    Column(' Total Backward Packets', 'total_backward_packets', 'int64'),
    Column('Total Length of Fwd Packets', 'total_length_of_fwd_packets', 'double'),
    Column(' Total Length of Bwd Packets', 'total_length_of_bwd_packets', 'double'),
    Column(' Fwd Packet Length Max', 'fwd_packet_length_max', 'double'),
    Column(' Fwd Packet Length Min', 'fwd_packet_length_min', 'double'),
    Column(' Fwd Packet Length Mean', 'fwd_packet_length_mean', 'double'),
    Column(' Fwd Packet Length Std', 'fwd_packet_length_std', 'double'),
    Column('Bwd Packet Length Max', 'bwd_packet_length_max', 'double'),
    Column(' Bwd Packet Length Min', 'bwd_packet_length_min', 'double'),
    Column(' Bwd Packet Length Mean', 'bwd_packet_length_mean', 'double'),
    Column(' Bwd Packet Length Std', 'bwd_packet_length_std', 'double'),
    Column('Flow Bytes/s', 'flow_bytes_s', 'double'),
    Column(' Flow Packets/s', 'flow_packets_s', 'double'),
    Column(' Flow IAT Mean', 'flow_iat_mean', 'double'),
    Column(' Flow IAT Std', 'flow_iat_std', 'double'),
    Column(' Flow IAT Max', 'flow_iat_max', 'double'),
    Column(' Flow IAT Min', 'flow_iat_min', 'double'),
    Column('Fwd IAT Total', 'fwd_iat_total', 'double'),
    Column(' Fwd IAT Mean', 'fwd_iat_mean', 'double'),
    Column(' Fwd IAT Std', 'fwd_iat_std', 'double'),
    Column(' Fwd IAT Max', 'fwd_iat_max', 'double'),
    Column(' Fwd IAT Min', 'fwd_iat_min', 'double'),
    Column('Bwd IAT Total', 'bwd_iat_total', 'double'),
    Column(' Bwd IAT Mean', 'bwd_iat_mean', 'double'),
    Column(' Bwd IAT Std', 'bwd_iat_std', 'double'),
    Column(' Bwd IAT Max', 'bwd_iat_max', 'double'),
    Column(' Bwd IAT Min', 'bwd_iat_min', 'double'),
    Column('Fwd PSH Flags', 'fwd_psh_flags', 'int64'),
    Column(' Bwd PSH Flags', 'bwd_psh_flags', 'int64'),
    Column(' Fwd URG Flags', 'fwd_urg_flags', 'int64'),
    Column(' Bwd URG Flags', 'bwd_urg_flags', 'int64'),
    Column(' Fwd Header Length', 'fwd_header_length', 'int64'),
    Column(' Bwd Header Length', 'bwd_header_length', 'int64'),
    Column('Fwd Packets/s', 'fwd_packets_s', 'double'),
    Column(' Bwd Packets/s', 'bwd_packets_s', 'double'),
    Column(' Min Packet Length', 'min_packet_length', 'double'),
    Column(' Max Packet Length', 'max_packet_length', 'double'),
    Column(' Packet Length Mean', 'packet_length_mean', 'double'),
    Column(' Packet Length Std', 'packet_length_std', 'double'),
    Column(' Packet Length Variance', 'packet_length_variance', 'double'),
    Column('FIN Flag Count', 'fin_flag_count', 'int64'),
    Column(' SYN Flag Count', 'syn_flag_count', 'int64'),
    Column(' RST Flag Count', 'rst_flag_count', 'int64'),
    Column(' PSH Flag Count', 'psh_flag_count', 'int64'),
    Column(' ACK Flag Count', 'ack_flag_count', 'int64'),
    Column(' URG Flag Count', 'urg_flag_count', 'int64'),
    Column(' CWE Flag Count', 'cwe_flag_count', 'int64'),
    Column(' ECE Flag Count', 'ece_flag_count', 'int64'),
    Column(' Down/Up Ratio', 'down_up_ratio', 'double'),
    Column(' Average Packet Size', 'average_packet_size', 'double'),
    Column(' Avg Fwd Segment Size', 'avg_fwd_segment_size', 'double'),
    Column(' Avg Bwd Segment Size', 'avg_bwd_segment_size', 'double'),
    Column(' Fwd Header Length', 'fwd_header_length_1', 'int64'),
    Column('Fwd Avg Bytes/Bulk', 'fwd_avg_bytes_bulk', 'int64'),
    Column(' Fwd Avg Packets/Bulk', 'fwd_avg_packets_bulk', 'int64'),
    Column(' Fwd Avg Bulk Rate', 'fwd_avg_bulk_rate', 'int64'),
    Column(' Bwd Avg Bytes/Bulk', 'bwd_avg_bytes_bulk', 'int64'),
    Column(' Bwd Avg Packets/Bulk', 'bwd_avg_packets_bulk', 'int64'),
    Column('Bwd Avg Bulk Rate', 'bwd_avg_bulk_rate', 'int64'),
    Column('Subflow Fwd Packets', 'subflow_fwd_packets', 'int64'),
    Column(' Subflow Fwd Bytes', 'subflow_fwd_bytes', 'int64'),
    Column(' Subflow Bwd Packets', 'subflow_bwd_packets', 'int64'),
    Column(' Subflow Bwd Bytes', 'subflow_bwd_bytes', 'int64'),
    Column('Init_Win_bytes_forward', 'init_win_bytes_forward', 'int64'),
    Column(' Init_Win_bytes_backward', 'init_win_bytes_backward', 'int64'),
    Column(' act_data_pkt_fwd', 'act_data_pkt_fwd', 'int64'),
    Column(' min_seg_size_forward', 'min_seg_size_forward', 'int64'),
    Column('Active Mean', 'active_mean', 'double'),
    Column(' Active Std', 'active_std', 'double'),
    Column(' Active Max', 'active_max', 'double'),
    Column(' Active Min', 'active_min', 'double'),
    Column('Idle Mean', 'idle_mean', 'double'),
    Column(' Idle Std', 'idle_std', 'double'),
    Column(' Idle Max', 'idle_max', 'double'),
    Column(' Idle Min', 'idle_min', 'double'),
    Column(' Label', 'label_raw', 'string'),
)

FLOWS_LABELS = (
    Label('BENIGN', 'benign', is_attack=False),
    Label('Bot', 'bot', is_attack=True),
    Label('DDoS', 'ddos', is_attack=True),
    Label('DoS GoldenEye', 'dos_goldeneye', is_attack=True),
    Label('DoS Hulk', 'dos_hulk', is_attack=True),
    Label('DoS Slowhttptest', 'dos_slowhttptest', is_attack=True),
    Label('DoS slowloris', 'dos_slowloris', is_attack=True),
    Label('FTP-Patator', 'ftp_patator', is_attack=True),
    Label('Heartbleed', 'heartbleed', is_attack=True),
    Label('Infiltration', 'infiltration', is_attack=True),
    Label('PortScan', 'portscan', is_attack=True),
    Label('SSH-Patator', 'ssh_patator', is_attack=True),
    Label('Web Attack \u2013 Brute Force', 'web_attack_brute_force', is_attack=True),
    Label('Web Attack \u2013 Sql Injection', 'web_attack_sql_injection', is_attack=True),
    Label('Web Attack \u2013 XSS', 'web_attack_xss', is_attack=True),
)

ML_FILES = (
    FileEntry(
        name='MachineLearningCSV.zip',
        sha256='c3f26274b36c837ccf28ffd2dbf4582941c30b3ee70a635c6e5b2f87c4727928',
        size=235102953,
        kind='archive',
    ),
    FileEntry(
        name='Monday-WorkingHours.pcap_ISCX.csv',
        sha256='852c4beb34eda186f32561fa79df7a0747e92e1a6535b01270820dd9ffe17f34',
        size=176927918,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Monday-WorkingHours.pcap_ISCX.csv',
        rows=529918,
    ),
    FileEntry(
        name='Tuesday-WorkingHours.pcap_ISCX.csv',
        sha256='52b8692ae8c7d2ed04671fe2b98335693c0a92c7ab157d8c8b534d6523080851',
        size=135078995,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv',
        rows=445909,
    ),
    FileEntry(
        name='Wednesday-workingHours.pcap_ISCX.csv',
        sha256='893c27dc968bf7a8adef1689f90be55ca4a4dc3088fb63d6ff247ac56856df2a',
        size=225166395,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Wednesday-workingHours.pcap_ISCX.csv',
        rows=692703,
    ),
    FileEntry(
        name='Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
        sha256='d67066211fb1689c78406f1506f4c44704ecb92088353d5c96d96d6474eb819d',
        size=52023263,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
        rows=170366,
    ),
    FileEntry(
        name='Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
        sha256='6bcda3857c2504676034e3ea57762d38393cc734cb377a726bd5cb153961b1b5',
        size=83102436,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
        rows=288602,
    ),
    FileEntry(
        name='Friday-WorkingHours-Morning.pcap_ISCX.csv',
        sha256='53a41c24d570ea83b7ac55b2e94df94e7a8216aeb80a2af0246b6bc8bb543000',
        size=58316725,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Friday-WorkingHours-Morning.pcap_ISCX.csv',
        rows=191033,
    ),
    FileEntry(
        name='Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
        sha256='ca1824c51bfbb7b3c72290a11be04366ba8815878c6a1cc5c44cb1cee269e99b',
        size=76906168,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
        rows=286467,
    ),
    FileEntry(
        name='Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
        sha256='6ff1580f5f81c0ae28a26f7631721018577f5f7c5e0feac28b795fcfe7b411ee',
        size=77123859,
        archive='MachineLearningCSV.zip',
        member='MachineLearningCVE/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
        rows=225745,
    ),
)

ML_COLUMNS = (
    Column(' Destination Port', 'destination_port', 'int64'),
    Column(' Flow Duration', 'flow_duration', 'int64'),
    Column(' Total Fwd Packets', 'total_fwd_packets', 'int64'),
    Column(' Total Backward Packets', 'total_backward_packets', 'int64'),
    Column('Total Length of Fwd Packets', 'total_length_of_fwd_packets', 'int64'),
    Column(' Total Length of Bwd Packets', 'total_length_of_bwd_packets', 'int64'),
    Column(' Fwd Packet Length Max', 'fwd_packet_length_max', 'int64'),
    Column(' Fwd Packet Length Min', 'fwd_packet_length_min', 'int64'),
    Column(' Fwd Packet Length Mean', 'fwd_packet_length_mean', 'double'),
    Column(' Fwd Packet Length Std', 'fwd_packet_length_std', 'double'),
    Column('Bwd Packet Length Max', 'bwd_packet_length_max', 'int64'),
    Column(' Bwd Packet Length Min', 'bwd_packet_length_min', 'int64'),
    Column(' Bwd Packet Length Mean', 'bwd_packet_length_mean', 'double'),
    Column(' Bwd Packet Length Std', 'bwd_packet_length_std', 'double'),
    Column('Flow Bytes/s', 'flow_bytes_s', 'double'),
    Column(' Flow Packets/s', 'flow_packets_s', 'double'),
    Column(' Flow IAT Mean', 'flow_iat_mean', 'double'),
    Column(' Flow IAT Std', 'flow_iat_std', 'double'),
    Column(' Flow IAT Max', 'flow_iat_max', 'int64'),
    Column(' Flow IAT Min', 'flow_iat_min', 'int64'),
    Column('Fwd IAT Total', 'fwd_iat_total', 'int64'),
    Column(' Fwd IAT Mean', 'fwd_iat_mean', 'double'),
    Column(' Fwd IAT Std', 'fwd_iat_std', 'double'),
    Column(' Fwd IAT Max', 'fwd_iat_max', 'int64'),
    Column(' Fwd IAT Min', 'fwd_iat_min', 'int64'),
    Column('Bwd IAT Total', 'bwd_iat_total', 'int64'),
    Column(' Bwd IAT Mean', 'bwd_iat_mean', 'double'),
    Column(' Bwd IAT Std', 'bwd_iat_std', 'double'),
    Column(' Bwd IAT Max', 'bwd_iat_max', 'int64'),
    Column(' Bwd IAT Min', 'bwd_iat_min', 'int64'),
    Column('Fwd PSH Flags', 'fwd_psh_flags', 'int64'),
    Column(' Bwd PSH Flags', 'bwd_psh_flags', 'int64'),
    Column(' Fwd URG Flags', 'fwd_urg_flags', 'int64'),
    Column(' Bwd URG Flags', 'bwd_urg_flags', 'int64'),
    Column(' Fwd Header Length', 'fwd_header_length', 'int64'),
    Column(' Bwd Header Length', 'bwd_header_length', 'int64'),
    Column('Fwd Packets/s', 'fwd_packets_s', 'double'),
    Column(' Bwd Packets/s', 'bwd_packets_s', 'double'),
    Column(' Min Packet Length', 'min_packet_length', 'int64'),
    Column(' Max Packet Length', 'max_packet_length', 'int64'),
    Column(' Packet Length Mean', 'packet_length_mean', 'double'),
    Column(' Packet Length Std', 'packet_length_std', 'double'),
    Column(' Packet Length Variance', 'packet_length_variance', 'double'),
    Column('FIN Flag Count', 'fin_flag_count', 'int64'),
    Column(' SYN Flag Count', 'syn_flag_count', 'int64'),
    Column(' RST Flag Count', 'rst_flag_count', 'int64'),
    Column(' PSH Flag Count', 'psh_flag_count', 'int64'),
    Column(' ACK Flag Count', 'ack_flag_count', 'int64'),
    Column(' URG Flag Count', 'urg_flag_count', 'int64'),
    Column(' CWE Flag Count', 'cwe_flag_count', 'int64'),
    Column(' ECE Flag Count', 'ece_flag_count', 'int64'),
    Column(' Down/Up Ratio', 'down_up_ratio', 'int64'),
    Column(' Average Packet Size', 'average_packet_size', 'double'),
    Column(' Avg Fwd Segment Size', 'avg_fwd_segment_size', 'double'),
    Column(' Avg Bwd Segment Size', 'avg_bwd_segment_size', 'double'),
    Column(' Fwd Header Length', 'fwd_header_length_1', 'int64'),
    Column('Fwd Avg Bytes/Bulk', 'fwd_avg_bytes_bulk', 'int64'),
    Column(' Fwd Avg Packets/Bulk', 'fwd_avg_packets_bulk', 'int64'),
    Column(' Fwd Avg Bulk Rate', 'fwd_avg_bulk_rate', 'int64'),
    Column(' Bwd Avg Bytes/Bulk', 'bwd_avg_bytes_bulk', 'int64'),
    Column(' Bwd Avg Packets/Bulk', 'bwd_avg_packets_bulk', 'int64'),
    Column('Bwd Avg Bulk Rate', 'bwd_avg_bulk_rate', 'int64'),
    Column('Subflow Fwd Packets', 'subflow_fwd_packets', 'int64'),
    Column(' Subflow Fwd Bytes', 'subflow_fwd_bytes', 'int64'),
    Column(' Subflow Bwd Packets', 'subflow_bwd_packets', 'int64'),
    Column(' Subflow Bwd Bytes', 'subflow_bwd_bytes', 'int64'),
    Column('Init_Win_bytes_forward', 'init_win_bytes_forward', 'int64'),
    Column(' Init_Win_bytes_backward', 'init_win_bytes_backward', 'int64'),
    Column(' act_data_pkt_fwd', 'act_data_pkt_fwd', 'int64'),
    Column(' min_seg_size_forward', 'min_seg_size_forward', 'int64'),
    Column('Active Mean', 'active_mean', 'double'),
    Column(' Active Std', 'active_std', 'double'),
    Column(' Active Max', 'active_max', 'int64'),
    Column(' Active Min', 'active_min', 'int64'),
    Column('Idle Mean', 'idle_mean', 'double'),
    Column(' Idle Std', 'idle_std', 'double'),
    Column(' Idle Max', 'idle_max', 'int64'),
    Column(' Idle Min', 'idle_min', 'int64'),
    Column(' Label', 'label_raw', 'string'),
)

ML_LABELS = (
    Label('BENIGN', 'benign', is_attack=False),
    Label('Bot', 'bot', is_attack=True),
    Label('DDoS', 'ddos', is_attack=True),
    Label('DoS GoldenEye', 'dos_goldeneye', is_attack=True),
    Label('DoS Hulk', 'dos_hulk', is_attack=True),
    Label('DoS Slowhttptest', 'dos_slowhttptest', is_attack=True),
    Label('DoS slowloris', 'dos_slowloris', is_attack=True),
    Label('FTP-Patator', 'ftp_patator', is_attack=True),
    Label('Heartbleed', 'heartbleed', is_attack=True),
    Label('Infiltration', 'infiltration', is_attack=True),
    Label('PortScan', 'portscan', is_attack=True),
    Label('SSH-Patator', 'ssh_patator', is_attack=True),
    Label('Web Attack \ufffd Brute Force', 'web_attack_brute_force', is_attack=True),
    Label('Web Attack \ufffd Sql Injection', 'web_attack_sql_injection', is_attack=True),
    Label('Web Attack \ufffd XSS', 'web_attack_xss', is_attack=True),
)
