"""CIC-IDS2017 as corrected by Engelen, Rimmer and Joosen (2021).

Every value below was read from the files downloaded from the official page
on 2026-10-09.
"""

from idsdata.model import Column, FileEntry, Label

ARCHIVE_URL = 'https://intrusion-detection.distrinet-research.be/WTMC2021/Dataset/dataset.zip'

FILES = (
    FileEntry(
        name='dataset.zip',
        sha256='4d535da19795d85376ae1397d161329e3b06fc47d9a5a68cd9be2cd7ecee0f2a',
        size=333841436,
        kind='archive',
        url=ARCHIVE_URL,
    ),
    FileEntry(
        name='Monday-WorkingHours.csv',
        sha256='580bc5b3a48ccaa9b61d6936bb88adb00a6a069a02c974e946bd324bc09971bc',
        size=208244807,
        archive='dataset.zip',
        rows=371749,
    ),
    FileEntry(
        name='Tuesday-WorkingHours.csv',
        sha256='59d60eff01526b511fa575a08a9a0e241674276adf1aa07471c947f7d733e19a',
        size=178453210,
        archive='dataset.zip',
        rows=322003,
    ),
    FileEntry(
        name='Wednesday-WorkingHours.csv',
        sha256='820446eb19713031827a1893871e30fb9da4c3b21ad5cd15d9a2ef6686a37583',
        size=291529516,
        archive='dataset.zip',
        rows=496779,
    ),
    FileEntry(
        name='Thursday-WorkingHours.csv',
        sha256='3db32a8e9a4da80aa15fd0bbf69733c8de8c6e6147fe279770eec1be6c263d65',
        size=187707525,
        archive='dataset.zip',
        rows=362368,
    ),
    FileEntry(
        name='Friday-WorkingHours.csv',
        sha256='8bf5a79222d2a553b75fe1ee81cc3ddff89b87befaef52e62368fdb2e3a79def',
        size=282607319,
        archive='dataset.zip',
        rows=547915,
    ),
)

COLUMNS = (
    Column('Flow ID', 'flow_id', 'string'),
    Column('Src IP', 'src_ip', 'string'),
    Column('Src Port', 'src_port', 'int64'),
    Column('Dst IP', 'dst_ip', 'string'),
    Column('Dst Port', 'dst_port', 'int64'),
    Column('Protocol', 'protocol', 'int64'),
    Column('Timestamp', 'timestamp', 'string'),
    Column('Flow Duration', 'flow_duration', 'int64'),
    Column('Total Fwd Packet', 'total_fwd_packet', 'int64'),
    Column('Total Bwd packets', 'total_bwd_packets', 'int64'),
    Column('Total Length of Fwd Packet', 'total_length_of_fwd_packet', 'double'),
    Column('Total Length of Bwd Packet', 'total_length_of_bwd_packet', 'double'),
    Column('Fwd Packet Length Max', 'fwd_packet_length_max', 'double'),
    Column('Fwd Packet Length Min', 'fwd_packet_length_min', 'double'),
    Column('Fwd Packet Length Mean', 'fwd_packet_length_mean', 'double'),
    Column('Fwd Packet Length Std', 'fwd_packet_length_std', 'double'),
    Column('Bwd Packet Length Max', 'bwd_packet_length_max', 'double'),
    Column('Bwd Packet Length Min', 'bwd_packet_length_min', 'double'),
    Column('Bwd Packet Length Mean', 'bwd_packet_length_mean', 'double'),
    Column('Bwd Packet Length Std', 'bwd_packet_length_std', 'double'),
    Column('Flow Bytes/s', 'flow_bytes_s', 'double'),
    Column('Flow Packets/s', 'flow_packets_s', 'double'),
    Column('Flow IAT Mean', 'flow_iat_mean', 'double'),
    Column('Flow IAT Std', 'flow_iat_std', 'double'),
    Column('Flow IAT Max', 'flow_iat_max', 'double'),
    Column('Flow IAT Min', 'flow_iat_min', 'double'),
    Column('Fwd IAT Total', 'fwd_iat_total', 'double'),
    Column('Fwd IAT Mean', 'fwd_iat_mean', 'double'),
    Column('Fwd IAT Std', 'fwd_iat_std', 'double'),
    Column('Fwd IAT Max', 'fwd_iat_max', 'double'),
    Column('Fwd IAT Min', 'fwd_iat_min', 'double'),
    Column('Bwd IAT Total', 'bwd_iat_total', 'double'),
    Column('Bwd IAT Mean', 'bwd_iat_mean', 'double'),
    Column('Bwd IAT Std', 'bwd_iat_std', 'double'),
    Column('Bwd IAT Max', 'bwd_iat_max', 'double'),
    Column('Bwd IAT Min', 'bwd_iat_min', 'double'),
    Column('Fwd PSH Flags', 'fwd_psh_flags', 'int64'),
    Column('Bwd PSH Flags', 'bwd_psh_flags', 'int64'),
    Column('Fwd URG Flags', 'fwd_urg_flags', 'int64'),
    Column('Bwd URG Flags', 'bwd_urg_flags', 'int64'),
    Column('Fwd Header Length', 'fwd_header_length', 'int64'),
    Column('Bwd Header Length', 'bwd_header_length', 'int64'),
    Column('Fwd Packets/s', 'fwd_packets_s', 'double'),
    Column('Bwd Packets/s', 'bwd_packets_s', 'double'),
    Column('Packet Length Min', 'packet_length_min', 'double'),
    Column('Packet Length Max', 'packet_length_max', 'double'),
    Column('Packet Length Mean', 'packet_length_mean', 'double'),
    Column('Packet Length Std', 'packet_length_std', 'double'),
    Column('Packet Length Variance', 'packet_length_variance', 'double'),
    Column('FIN Flag Count', 'fin_flag_count', 'int64'),
    Column('SYN Flag Count', 'syn_flag_count', 'int64'),
    Column('RST Flag Count', 'rst_flag_count', 'int64'),
    Column('PSH Flag Count', 'psh_flag_count', 'int64'),
    Column('ACK Flag Count', 'ack_flag_count', 'int64'),
    Column('URG Flag Count', 'urg_flag_count', 'int64'),
    Column('CWR Flag Count', 'cwr_flag_count', 'int64'),
    Column('ECE Flag Count', 'ece_flag_count', 'int64'),
    Column('Down/Up Ratio', 'down_up_ratio', 'double'),
    Column('Average Packet Size', 'average_packet_size', 'double'),
    Column('Fwd Segment Size Avg', 'fwd_segment_size_avg', 'double'),
    Column('Bwd Segment Size Avg', 'bwd_segment_size_avg', 'double'),
    Column('Fwd Bytes/Bulk Avg', 'fwd_bytes_bulk_avg', 'int64'),
    Column('Fwd Packet/Bulk Avg', 'fwd_packet_bulk_avg', 'int64'),
    Column('Fwd Bulk Rate Avg', 'fwd_bulk_rate_avg', 'int64'),
    Column('Bwd Bytes/Bulk Avg', 'bwd_bytes_bulk_avg', 'int64'),
    Column('Bwd Packet/Bulk Avg', 'bwd_packet_bulk_avg', 'int64'),
    Column('Bwd Bulk Rate Avg', 'bwd_bulk_rate_avg', 'int64'),
    Column('Subflow Fwd Packets', 'subflow_fwd_packets', 'int64'),
    Column('Subflow Fwd Bytes', 'subflow_fwd_bytes', 'int64'),
    Column('Subflow Bwd Packets', 'subflow_bwd_packets', 'int64'),
    Column('Subflow Bwd Bytes', 'subflow_bwd_bytes', 'int64'),
    Column('FWD Init Win Bytes', 'fwd_init_win_bytes', 'int64'),
    Column('Bwd Init Win Bytes', 'bwd_init_win_bytes', 'int64'),
    Column('Fwd Act Data Pkts', 'fwd_act_data_pkts', 'int64'),
    Column('Fwd Seg Size Min', 'fwd_seg_size_min', 'int64'),
    Column('Active Mean', 'active_mean', 'double'),
    Column('Active Std', 'active_std', 'double'),
    Column('Active Max', 'active_max', 'double'),
    Column('Active Min', 'active_min', 'double'),
    Column('Idle Mean', 'idle_mean', 'double'),
    Column('Idle Std', 'idle_std', 'double'),
    Column('Idle Max', 'idle_max', 'double'),
    Column('Idle Min', 'idle_min', 'double'),
    Column('Label', 'label_raw', 'string'),
)

LABELS = (
    Label('BENIGN', 'benign', is_attack=False),
    Label('Bot', 'bot', is_attack=True),
    Label('Bot - Attempted', 'bot_attempted', is_attack=False, is_attempted=True),
    Label('DDoS', 'ddos', is_attack=True),
    Label('DoS GoldenEye', 'dos_goldeneye', is_attack=True),
    Label('DoS GoldenEye - Attempted', 'dos_goldeneye_attempted', is_attack=False, is_attempted=True),
    Label('DoS Hulk', 'dos_hulk', is_attack=True),
    Label('DoS Hulk - Attempted', 'dos_hulk_attempted', is_attack=False, is_attempted=True),
    Label('DoS Slowhttptest', 'dos_slowhttptest', is_attack=True),
    Label('DoS Slowhttptest - Attempted', 'dos_slowhttptest_attempted', is_attack=False, is_attempted=True),
    Label('DoS slowloris', 'dos_slowloris', is_attack=True),
    Label('DoS slowloris - Attempted', 'dos_slowloris_attempted', is_attack=False, is_attempted=True),
    Label('FTP-Patator', 'ftp_patator', is_attack=True),
    Label('FTP-Patator - Attempted', 'ftp_patator_attempted', is_attack=False, is_attempted=True),
    Label('Heartbleed', 'heartbleed', is_attack=True),
    Label('Infiltration', 'infiltration', is_attack=True),
    Label('Infiltration - Attempted', 'infiltration_attempted', is_attack=False, is_attempted=True),
    Label('PortScan', 'portscan', is_attack=True),
    Label('SSH-Patator', 'ssh_patator', is_attack=True),
    Label('SSH-Patator - Attempted', 'ssh_patator_attempted', is_attack=False, is_attempted=True),
    Label('Web Attack - Brute Force', 'web_attack_brute_force', is_attack=True),
    Label(
        'Web Attack - Brute Force - Attempted', 'web_attack_brute_force_attempted', is_attack=False, is_attempted=True
    ),
    Label('Web Attack - Sql Injection', 'web_attack_sql_injection', is_attack=True),
    Label('Web Attack - XSS', 'web_attack_xss', is_attack=True),
    Label('Web Attack - XSS - Attempted', 'web_attack_xss_attempted', is_attack=False, is_attempted=True),
)
